name: flutter_cab
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  awesome_notifications: ^0.0.6+7
  google_maps_flutter: ^1.2.0
  flutter_rating_bar: ^1.3.0+1
  intl: ^0.15.7
  #flutter_svg: 0.18.0
  #http: ^0.12.0+4
  provider: ^4.1.3
  otp_screen: ^0.0.3
  datetime_picker_formfield: ^1.0.0
  image_picker: ^0.6.0+9
  shared_preferences: ^0.5.6+1
  google_maps_place_picker: ^1.0.1
  geolocator: ^6.2.1
  flutter_polyline_points: ^0.1.0
  flutter_launcher_icons: ^0.8.0
  floating_bottom_navigation_bar: ^1.4.1
  socket_io_client: ^0.9.12
  web_socket_channel: ^1.1.0
  flutter_map: ^0.11.0
  latlong: ^0.6.1
  #latlong2: ^0.8.0
  #geolocator: ^5.3.1
  #nominatim_location_picker: any
  get: ^3.26.0
  http: ^0.12.1
  material_floating_search_bar: ^0.2.6
  material_design_icons_flutter: 4.0.5955
  implicitly_animated_reorderable_list: ^0.3.2
  flutter_map_tappable_polyline: ^1.3.0+1
  google_places_flutter: ^2.0.3
  url_launcher: ^5.7.10
  geocoding: ^1.0.5
  syncfusion_flutter_maps: ^18.4.49-beta
  lottie: ^0.7.0+1
  fluttertoast: ^6.0.1
  flutter_spinkit: ^3.1.0




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_src_main_ic_launcher-playstore.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  #pedantic: 1.9.0
  shared_preferences: ^0.5.6+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/ic_logo.png
   - images/map-marker.png
   - images/navigation.png
   - images/car.png
   - images/city.png
   - images/hatchback.png
   - images/tuk.png
   - images/van.png
   - images/driver.jpg
   - images/driver_img.jpg
   - images/stopwatch.png
   - images/ic_close.png
   - images/ic_facebook.png
   - images/ic_twitter.png
   - images/ic_instagram.png
   - images/payments/cash.png
   - images/payments/card.png
   - images/payments/points.png
   - images/menu/user.png
   - images/menu/payment.png
   - images/menu/book_later.png
   - images/menu/my_trips.png
   - images/menu/rate_card.png
   - images/menu/news_offers.png
   - images/menu/emergency_contacts.png
   - images/menu/help_support.png
   - images/
   - images/undraw_Order_ride_re_372k.svg
   - images/pickup_location_marker.png
   - images/green_location_icon.png
   - images/location_on_map.png
   - images/preloader.gif
   - images/user_dashboard/dashboard_office.png
   - images/user_dashboard/dashboard_office_2.png
   - images/user_dashboard/dashboard_vehicle_service.png
   - images/user_dashboard/tab_car.png
   - images/user_dashboard/tab_foods.png
   - images/user_dashboard/tab_package.png
   - images/user_dashboard/taxime_logo.png
   - images/user_dashboard/drawer_header_1.png
   - images/user_dashboard/drawer_header_2.png
   - images/user_dashboard/drawer_header_3.png
   - images/user_dashboard/favourite_places.png
   - images/user_dashboard/recent_places.png
   - images/user_dashboard/travel_car.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Black.ttf
          weight: 900

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
